### ISSUE TITLE
Get Expenses

### ISSUE THREAD

**Issue by venkatakrishnan-srinivasaraj** [dc297/webscrapercs#2]
- [x] Able to scrap the Expenses data from the website.
- [x] Tested the code and ensuring it is working fine.

**Comment by venkatakrishnan-srinivasaraj** [comment]
@Eaglecomet1318 

There are many compilation errors. So can you please rework on this and get that one working?
Lets have a call if you are facing any problems with database so that you can test them locally.

**Comment by Eaglecomet1318** [comment]
I’ll call and get my database problems resolved before lunch (I have a test in the morning to study for).

Specifically which areas? I’ll get started on rewriting the code as soon as I can.
