### ISSUE TITLE
Get Amenities

### ISSUE THREAD

**Issue by venkatakrishnan-srinivasaraj** [dc297/webscrapercs#3]
- [x] Able to scrap the Amenities data from the website.
- [x] Tested the code and ensuring it is working fine.

**Comment by venkatakrishnan-srinivasaraj** [comment]
@Eaglecomet1318 
Are you doing this? 
Bcoz the slack conversation says so and I'm not sure that were you aware of this?

**Comment by Eaglecomet1318** [comment]
That was assigned at the meeting day before yesterday, but as far as I know, no one actually wrote it yet. Currently the priority new code that I’m working on right now (any corrections notwithstanding)
